server:
  addr: ":8080"
  basePath: "/aggregator"
db:
  connection: "postgres://localhost:5432/aggregator?user=aggregator&password=CeithieZ5a&sslmode=disable"
  maxIdleConnections: 16
  maxOpenConnections: 16
log:
  title: app-aggregator
  type: stdout
  level: trace
  formatter: json
tracing:
  probability: 1.0
  jaeger:
    service_name: "app-aggregator"
    collector_address: "http://localhost:14268/api/traces"
